runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public
  static_dir: public

- url: /search
  script: search.app

- url: /upload
  script: upload.app

- url: /
  script: map.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest

- name: google-cloud-datastore
  version: latest
