from google.appengine.ext import db

class Record(db.Model):
    id = db.StringProperty(required=True)
    created = db.DateTimeProperty()
    user = db.UserProperty()
    date = db.DateProperty()
    firstName = db.StringProperty()
    lastName = db.StringProperty()
    ethnicity = db.StringProperty()
    gender = db.StringProperty()
    age = db.IntegerProperty()
    ability = db.BooleanProperty()
    oFirstName = db.StringProperty()
    oLastName = db.StringProperty()
    badge = db.StringProperty()
    oRace = db.StringProperty()
    dept = db.StringProperty()
    about = db.TextProperty()
    lat = db.FloatProperty()
    lng = db.FloatProperty()
    country = db.StringProperty()
    state = db.StringProperty()
    city_state = db.StringProperty()
    city = db.StringProperty()
    neighborhood = db.StringProperty()
    zipCode = db.StringProperty()
    brutal = db.StringProperty()
    fatal = db.BooleanProperty()
    wrongful = db.BooleanProperty()
    interaction = db.BooleanProperty()
    promoted = db.IntegerProperty()
    flagged = db.BooleanProperty()
    raw = db.StringProperty()
    webm = db.StringProperty()
    ogg = db.StringProperty()
    mp4 = db.StringProperty()
    views = db.IntegerProperty()